Repository MrTanoshii/PyWeek-33-Metro, pull requests merged in 2022-03, with the labels that each got.

#3 Update README for selected theme & library
  README.md
Labels: documentation

#18 Implement enemy drops
  bg.py
  bullet.py
  constants.py
  enemy.py
  gameview.py
  gold.py
  lib.py
  player.py
  resources/images/donky-example-player.png
  resources/images/tank_enemy.png
  settings.py
  tracker.py
Labels: enhancement

#29 Fix bullet & refactor player movement
  constants.py
  gameview.py
  player.py
Labels: bug

#32 Implement weapon system
  bullet.py
  constants.py
  enemy.py
  gameview.py
  player.py
  resources/images/weapon/weapon_ak/bullet/1.png
  resources/images/weapon/weapon_ak/weapon_ak.png
  resources/images/weapon/weapon_rpg/bullet/1.png
  resources/images/weapon/weapon_rpg/bullet/10.png
  resources/images/weapon/weapon_rpg/bullet/11.png
  resources/images/weapon/weapon_rpg/bullet/12.png
  resources/images/weapon/weapon_rpg/bullet/13.png
  resources/images/weapon/weapon_rpg/bullet/14.png
  resources/images/weapon/weapon_rpg/bullet/15.png
  resources/images/weapon/weapon_rpg/bullet/16.png
  resources/images/weapon/weapon_rpg/bullet/17.png
  resources/images/weapon/weapon_rpg/bullet/18.png
  resources/images/weapon/weapon_rpg/bullet/19.png
  resources/images/weapon/weapon_rpg/bullet/2.png
  resources/images/weapon/weapon_rpg/bullet/20.png
  resources/images/weapon/weapon_rpg/bullet/21.png
  resources/images/weapon/weapon_rpg/bullet/22.png
  resources/images/weapon/weapon_rpg/bullet/23.png
  resources/images/weapon/weapon_rpg/bullet/24.png
  resources/images/weapon/weapon_rpg/bullet/3.png
  resources/images/weapon/weapon_rpg/bullet/4.png
  resources/images/weapon/weapon_rpg/bullet/5.png
  resources/images/weapon/weapon_rpg/bullet/6.png
  resources/images/weapon/weapon_rpg/bullet/7.png
  resources/images/weapon/weapon_rpg/bullet/8.png
  resources/images/weapon/weapon_rpg/bullet/9.png
  resources/images/weapon/weapon_rpg/weapon_rpg.png
  weapon.py
Labels: enhancement

#37 Bug fix: Pause menu
  gameview.py
Labels: bug

#54 Weapon reloading fix
  player.py
  weapon.py
Labels: bug, documentation

#57 Day 5 Bug squashing
  audio.py
  gameview.py
  mapview.py
  pause_menu_view.py
  player.py
  weapon.py
Labels: bug

#52 Shop
  .gitignore
  constants.py
  gameview.py
  mapview.py
  pause_menu_view.py
  resources/images/crosshair.png
  resources/images/map/gold-ingot.png
  resources/images/map/temp_shop.png
  shopview.py
Labels: enhancement

#70 Split constants.py into smaller files
  audio.py
  bg.py
  bullet.py
  const/audio.py
  const/constants.py
  const/death.py
  const/debug.py
  const/enemy.py
  const/enemy_weapon.py
  const/gold.py
  const/map.py
  const/player.py
  const/scale.py
  const/view.py
  const/view_game.py
  const/view_menu.py
  const/weapon.py
  const/weapon_fire.py
  const/window.py
  constants.py
  enemy.py
  gamedata.py
  gameview.py
  gold.py
  main.py
  mainmenu.py
  mapview.py
  pause_menu_view.py
  player.py
  settings.py
  shopview.py
  weapon.py
Labels: enhancement, good first issue

#71 Refactor weapon system
  const/enemy_weapon.py
  const/view_game.py
  const/weapon.py
  const/weapon_fire.py
  enemy.py
  gameview.py
  lib.py
  player.py
  weapon.py
Labels: bug, enhancement

#78 refactor: Implement a true global scale
  bg.py
  bullet.py
  const/constants.py
  const/enemy.py
  const/enemy_weapon.py
  const/map.py
  const/player.py
  const/scale.py
  const/view_pause.py
  const/weapon.py
  enemy.py
  gameview.py
  gold.py
  lib.py
  mainmenu.py
  mapview.py
  pause_menu_view.py
  player.py
  shopview.py
  weapon.py
Labels: enhancement

#87 feat: Upload meow sfx for easter egg
  const/audio.py
  resources/audio/ui/415209__inspectorj__cat-screaming-a.wav
  resources/audio/ui/README.md
Labels: enhancement

#85 Pause view
  const/audio.py
  pause_menu_view.py
  resources/images/pause_view/btn_back_to_map.png
  resources/images/pause_view/btn_main_menu.png
  resources/images/pause_view/btn_quit_game.png
  resources/images/pause_view/btn_resume.png
  resources/images/pause_view/screen_pause.png
Labels: enhancement

#91 feat: Implement easter egg
  audio.py
  const/audio.py
  pause_menu_view.py
  tracker.py
Labels: enhancement

#86 Implement basic enemy shooting logic
  bullet.py
  const/debug.py
  const/enemy_weapon.py
  enemy.py
  gameview.py
Labels: enhancement

#95 Player animation
  const/player.py
  gameview.py
  player.py
Labels: enhancement

#104 Cursor animation
  gameview.py
Labels: enhancement

#116 Py week 33 major bug fixes
  README.md
  const/window.py
  mapview.py
  run_game.py
Labels: bug, enhancement

#120 Website
  docs/index.css
  docs/index.html
  docs/index.js
Labels: documentation

#122 Fix major bugs from PyWeek midnight version
  const/window.py
  main.py
  pyweek docs/README
  pyweek docs/Screenshot 01.png
  pyweek docs/Screenshot 02.png
  pyweek docs/Screenshot 03.png
  pyweek docs/Screenshot 04.png
  pyweek docs/Screenshot 05.png
  weapon.py
Labels: bug

#124 Various bug and lint fixes
  .gitignore
  audio.py
  bullet.py
  enemy.py
  gamedata.py
  gameview.py
  gold.py
  main.py
  mapview.py
  pause_menu_view.py
  player.py
  settings.py
  story_view.py
  weapon.py
Labels: bug, documentation

#128 arcade update to 2.6.13
  requirements.txt
Labels: enhancement
