Repository MrTanoshii/PyWeek-33-Metro, pull requests merged in 2022-04, with the labels that each got.

#131 player gets pushed to left side of screen
  player.py
Labels: enhancement

#132 Implement Code coverage
  .github/workflows/code_coverage.yml
  .github/workflows/python_check.yml
  lib.py
  test/test_calculate_angle.py
Labels: enhancement

#139 Code clean up
  audio.py
  bullet.py
  enemy.py
  game_over_view.py
  gamedata.py
  gameview.py
  gold.py
  mapview.py
  pause_menu_view.py
  player.py
  shopview.py
  story_view.py
  weapon.py
Labels: bug, documentation

#138 Over reload fix
  weapon.py
Labels: bug

#143 Better controls
  src/view/game.py
  src/view/game_over.py
  src/view/main_menu.py
  src/view/map.py
  src/view/pause_menu.py
  src/view/quit.py
  src/view/shop.py
  src/view/story.py
Labels: bug, enhancement
